paths:
  /api/products:
    get:
      summary: Obtiene la lista de productos.
      description: Retorna todos los productos disponibles en el sistema. Solo accesible para usuarios autenticados con roles `admin` o `user`.
      tags:
        - Products
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de productos obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        "401":
          description: No autorizado. Token JWT inválido o no proporcionado.
        "500":
          description: Error interno al obtener los productos.

    post:
      summary: Crea un nuevo producto.
      description: Permite al usuario con rol `admin` crear un nuevo producto en la base de datos.
      tags:
        - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: Producto creado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto creado correctamente.
                  payload:
                    $ref: "#/components/schemas/Product"
        "401":
          description: No autorizado. Solo `admin` puede crear productos.
        "500":
          description: Error interno al crear el producto.

  /api/products/{pid}:
    get:
      summary: Obtiene el detalle de un producto por ID.
      description: Retorna la información detallada de un producto específico. Solo accesible para `admin` o `user`.
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto.
          schema:
            type: string
            example: 6720ab9e4f12a44b88b12345
      responses:
        "200":
          description: Detalle del producto obtenido correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado.
        "401":
          description: No autorizado.
        "500":
          description: Error interno al obtener el producto.

    put:
      summary: Actualiza un producto existente.
      description: Permite modificar la información de un producto existente. Solo disponible para usuarios con rol `admin`.
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a actualizar.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "200":
          description: Producto actualizado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto actualizado correctamente.
        "401":
          description: No autorizado. Solo `admin` puede actualizar productos.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno al actualizar el producto.

    delete:
      summary: Elimina un producto existente.
      description: Elimina un producto de la base de datos por su ID. Solo accesible para usuarios con rol `admin`.
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a eliminar.
          schema:
            type: string
            example: 6720ab9e4f12a44b88b12345
      responses:
        "200":
          description: Producto eliminado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Producto eliminado correctamente.
        "401":
          description: No autorizado. Solo `admin` puede eliminar productos.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno al eliminar el producto.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          example: 6720ab9e4f12a44b88b12345
        title:
          type: string
          example: Notebook Lenovo IdeaPad
        description:
          type: string
          example: Laptop con procesador AMD Ryzen 5 y 8GB de RAM.
        price:
          type: number
          example: 350000
        stock:
          type: integer
          example: 25
        category:
          type: string
          example: Tecnología
        owner:
          type: string
          example: admin
    ProductInput:
      type: object
      required:
        - title
        - description
        - price
        - stock
        - category
      properties:
        title:
          type: string
          example: Smartwatch Xiaomi Mi Band 8
        description:
          type: string
          example: Reloj inteligente con pantalla AMOLED y seguimiento de actividad física.
        price:
          type: number
          example: 60000
        stock:
          type: integer
          example: 50
        category:
          type: string
          example: Tecnología
