paths:
  /products:
    get:
      summary: Renderiza la vista con el listado de productos.
      tags:
        - Products Views
      responses:
        "200":
          description: Vista de productos renderizada exitosamente.
        "500":
          description: Error interno del servidor.

  /products/{pid}:
    get:
      summary: Renderiza la vista con el detalle de un producto específico.
      tags:
        - Views - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto.
          schema:
            type: string
      responses:
        "200":
          description: Vista del detalle del producto renderizada exitosamente.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor.

  /products/create:
    get:
      summary: Renderiza la vista para crear un nuevo producto.
      tags:
        - Views - Products
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Vista de creación de producto renderizada exitosamente.
        "401":
          description: No autorizado. El usuario no tiene permisos de administrador.
        "500":
          description: Error interno del servidor.

    post:
      summary: Procesa el formulario para crear un nuevo producto.
      tags:
        - Views - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
              required:
                - title
                - price
                - stock
      responses:
        "302":
          description: Redirección tras crear el producto exitosamente.
        "401":
          description: No autorizado.
        "500":
          description: Error interno del servidor.

  /products/{pid}/edit:
    get:
      summary: Renderiza la vista para editar un producto existente.
      tags:
        - Views - Products
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a editar.
          schema:
            type: string
      responses:
        "200":
          description: Vista de edición de producto renderizada exitosamente.
        "401":
          description: No autorizado.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor.

    post:
      summary: Procesa la actualización de un producto existente.
      tags:
        - Views - Products
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a actualizar.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
      responses:
        "302":
          description: Redirección tras editar el producto exitosamente.
        "401":
          description: No autorizado.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor.

  /products/{pid}/delete:
    post:
      summary: Elimina un producto existente y redirige.
      tags:
        - Views - Products
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a eliminar.
          schema:
            type: string
      responses:
        "302":
          description: Redirección tras eliminar el producto exitosamente.
        "401":
          description: No autorizado.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error interno del servidor.
